// =============================================================================
// GENERATED FILE - DO NOT EDIT BY HAND.
// Regenerated by tool/bump_version.dart on every real build (see build.sh /
// build.bat), which run this script before `flutter build`. Mirrors the
// `version:` line in pubspec.yaml at the moment of the last build.
// =============================================================================

const String kAppVersion = '1.0.2';
const int kAppBuildNumber = 3;
const String kAppVersionFull = '1.0.2+3';
