// =============================================================================
// GENERATED FILE - DO NOT EDIT BY HAND.
// Regenerated by tool/bump_version.dart on every real build (see build.sh /
// build.bat), which run this script before `flutter build`. Mirrors the
// `version:` line in pubspec.yaml at the moment of the last build.
// =============================================================================

const String kAppVersion = '0.0.7';
const int kAppBuildNumber = 7;
const String kAppVersionFull = '0.0.7+7';
