// =============================================================================
// HYDRA-UMC CONTROL (iOS/Flutter) - tool/bump_version.dart
// Copyright (C) 2026 JuanenRac (Electro Hobby 3D) <electrohobby3d@gmail.com>
// GPL-3.0 - see LICENSE
//
// Ecosystem-wide version policy: the version bumps automatically on every
// real build, no manual editing of pubspec.yaml. Run by build.sh/build.bat
// BEFORE `flutter build`, never by hand.
//
// Rule ("odometer", base 10):
//   - patch +1 on every build.
//   - if patch would go above 9, it resets to 0 and minor +1 instead
//     (example: 0.0.9 -> 0.1.0). Major is never touched by this script.
//   - build-number (the part after "+") is a plain monotonic counter,
//     always +1, no carry.
//
// This script is intentionally dependency-free (dart:io only) so it can run
// with `dart run` before `flutter pub get` has necessarily finished, and so
// no new pub package is needed just to bump a version string.
//
// It also regenerates lib/app_version.dart, a small generated constants
// file the app itself imports at runtime to show its own version in the UI
// (Settings screen) without adding a runtime dependency like
// package_info_plus purely for this.
// =============================================================================

import 'dart:io';

final _versionLine = RegExp(r'^version:\s*(\d+)\.(\d+)\.(\d+)\+(\d+)\s*$', multiLine: true);

void main() {
  final repoRoot = _findRepoRoot();
  final pubspecFile = File('${repoRoot.path}/pubspec.yaml');
  final generatedFile = File('${repoRoot.path}/lib/app_version.dart');

  if (!pubspecFile.existsSync()) {
    stderr.writeln('[bump_version] ERROR: pubspec.yaml not found at ${pubspecFile.path}');
    exit(1);
  }

  final contents = pubspecFile.readAsStringSync();
  final match = _versionLine.firstMatch(contents);
  if (match == null) {
    stderr.writeln('[bump_version] ERROR: could not find a "version: X.Y.Z+B" line in pubspec.yaml');
    exit(1);
  }

  final major = int.parse(match.group(1)!);
  var minor = int.parse(match.group(2)!);
  var patch = int.parse(match.group(3)!);
  final buildNumber = int.parse(match.group(4)!);

  final rawPatch = patch + 1;
  if (rawPatch > 9) {
    patch = 0;
    minor += 1;
  } else {
    patch = rawPatch;
  }
  final newBuildNumber = buildNumber + 1;

  final newVersionName = '$major.$minor.$patch';
  final newVersionLine = 'version: $newVersionName+$newBuildNumber';

  final newContents = contents.replaceRange(match.start, match.end, newVersionLine);
  pubspecFile.writeAsStringSync(newContents);

  generatedFile.parent.createSync(recursive: true);
  generatedFile.writeAsStringSync('''
// =============================================================================
// GENERATED FILE - DO NOT EDIT BY HAND.
// Regenerated by tool/bump_version.dart on every real build (see build.sh /
// build.bat), which run this script before `flutter build`. Mirrors the
// `version:` line in pubspec.yaml at the moment of the last build.
// =============================================================================

const String kAppVersion = '$newVersionName';
const int kAppBuildNumber = $newBuildNumber;
const String kAppVersionFull = '$newVersionName+$newBuildNumber';
''');

  stdout.writeln(
      '[bump_version] version bumped: $major.${match.group(2)}.${match.group(3)}+$buildNumber -> $newVersionLine');
}

/// Walks up from the script's own location to find the directory containing
/// pubspec.yaml, so this works regardless of the caller's current directory
/// (build.sh/build.bat invoke it as `dart run tool/bump_version.dart` from
/// the repo root, but this keeps it robust either way).
Directory _findRepoRoot() {
  var dir = File(Platform.script.toFilePath()).parent;
  while (true) {
    if (File('${dir.path}/pubspec.yaml').existsSync()) return dir;
    final parent = dir.parent;
    if (parent.path == dir.path) {
      // Fell through to filesystem root without finding it - fall back to
      // the current working directory (covers `dart run` invocations where
      // Platform.script resolution is unusual).
      return Directory.current;
    }
    dir = parent;
  }
}
